# echo -e "${YC}Downloading frontend artifacts...${NC}"
# curl -L -o /tmp/frontend.tar.gz https://raw.githubusercontent.com/raghudevopsb88/wealth-project/main/artifacts/frontend.tar.gz &>>$OUTPUT
# mkdir -p /tmp/frontend &>>$OUTPUT
# cd /tmp
# tar xzf /tmp/frontend.tar.gz &>>$OUTPUT
# status_check

# echo -e "${YC}Deploying frontend application...${NC}"
# cd /tmp/frontend
# npm ci &>>$OUTPUT
# npm run build &>>$OUTPUT
# status_check

# echo -e "${YC}Copying frontend build to nginx html directory...${NC}"
# rm -rf /usr/share/nginx/html/* &>>$OUTPUT
# cp -r /tmp/dist/* /usr/share/nginx/html/ &>>$OUTPUT
# status_check

# echo -e "${YC}Starting nginx service...${NC}"
# systemctl enable nginx &>>$OUTPUT
# systemctl restart nginx &>>$OUTPUT
# status_check

- name: Frontend Setup          # Human-readable name for this play (shows in terminal output)
  hosts: all                    # Which hosts from inventory to target (all = every host listed)
  become: true                  # Escalate privileges (equivalent to running as sudo)
  tasks:                        # List of actions to perform on the target hosts
  
    - name: Install nginx webserver and nodejs    # Task name — shows in output, helps debug failures
      ansible.builtin.dnf:               # Module to use — dnf is the package manager (RHEL/Amazon Linux)
        name: 
          - '@nginx:1.26'
          - nodejs                # Package to install — @ means it's a module stream, not a plain package
        state: present                   # Desired state — present=install it, absent=remove it, latest=upgrade it
      
    - name: Update nginx config file
      ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

    - name: Install nodejs repo failure
      ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_22.x | bash -

    - name: Download and extract nginx artifacts
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb88/wealth-project/main/artifacts/frontend.tar.gz
        dest: /tmp/
        remote_src: yes
