- name: Postgres Database Setup       
  hosts: all                   
  become: true                 
  tasks:
    - name: Install PostgreSQL Repository
      ansible.builtin.dnf:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present
        disable_gpg_check: true

    - name: Disable default postgres module
      ansible.builtin.shell: dnf -qy module disable postgresql

    - name: Install Postgres
      ansible.builtin.dnf:
        state: present
        name:
          - "postgresql16-server"
          - "postgresql16"

    - name: Check if DB already initialized
      ansible.builtin.stat:
        path: /var/lib/pgsql/16/data/PG_VERSION
      register: pgdata      

    - name: Initialize Database
      ansible.buildin.shell: /usr/pgsql-16/bin/postgresql-16-setup initdb
      when: not pgdata.stat.exists   # only runs if NOT already initialized, ignore_errors: yes (if this task fails, just note it and keep going.)

    - name: Update listen_addresses in postgresql.conf
      ansible.builtin.shell: sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /var/lib/pgsql/16/data/postgresql.conf

    # - name: Add remote access rule to pg_hba.conf
    #   ansible.builtin.lineinfile:  #Manages a single line inside a file — add it, remove it, or replace it. Idempotent by default.
    #     path: /var/lib/pgsql/16/data/pg_hba.conf
    #     line: "host    all    all    0.0.0.0/0    scram-sha-256"

    # - name: Update local auth to trust in pg_hba.conf
    #   ansible.builtin.shell: sed -i 's/local   all             all                                     peer/local   all             all                                     trust/' /var/lib/pgsql/16/data/pg_hba.conf

    - name: Copy pg_hba.conf file
      ansible.builtin.copy:
        src: pg_hba.conf
        dest: /var/lib/pgsql/16/data/pg_hba.conf     

    - name: Start PostgreSQL Service
      ansible.builtin.systemd_service:
        state: restarted
        name: postgresql16   
        enabled: true
      
    - name: Copy schema file
      ansible.builtin.copy:
        src: setup.sql
        dest: /tmp/setup.sql

    - name: Load schema
      ansible.builtin.shell: sudo -u postgres /usr/pgsql-16/bin/psql < /tmp/setup.sql